---
  root: true
  overrides:
    -
      files:
        - '*.ts'
      extends:
        - plugin:@angular-eslint/recommended
        - airbnb-typescript/base
      parserOptions:
        createDefaultProgram: true
        project:
          - tsconfig.*?.json
          - e2e/tsconfig.json
      rules:
        "@typescript-eslint/no-unused-vars": off
        "@typescript-eslint/no-unused-vars-experimental": error
        sort-imports:
          - error
          - ignoreCase: true
            ignoreDeclarationSort: true
            ignoreMemberSort: true
            memberSyntaxSortOrder:
              - none
              - all
              - multiple
              - single
            allowSeparatedGroups: true
    -
      files :
        - '*.component.html'
      extends:
        - plugin:@angular-eslint/template/recommended
    -
      files :
        - '*.component.ts'
      extends:
        - plugin:@angular-eslint/template/process-inline-templates
    -
      files:
        - src/**/*.spec.ts
        - src/**/*.d.ts
      parserOptions:
        project:
          - tsconfig.spec.json
      extends:
        - plugin:jasmine/recommended
      plugins:
        - jasmine
      env:
         jasmine: true
